// GENERATED by scripts/gen_palette.py -- do not edit.
// 24 fixed action-set palette entries, 13 bits each (rtl/ISA_NOTES.md section 5).
// Contents from isa_bench/ (hybridsweep.py recipe, in-sample over all five benchmarks).
`ifndef STT_PALETTE_ROM_VH
`define STT_PALETTE_ROM_VH

`define STT_PAL_00 13'h0000   // (empty)
`define STT_PAL_01 13'h0080   // c2dec
`define STT_PAL_02 13'h0040   // c2load
`define STT_PAL_03 13'h0C00   // call
`define STT_PAL_04 13'h0020   // cdec
`define STT_PAL_05 13'h0008   // cload
`define STT_PAL_06 13'h0010   // cload_b
`define STT_PAL_07 13'h0018   // cload_c
`define STT_PAL_08 13'h0004   // clr
`define STT_PAL_09 13'h0400   // crcrst
`define STT_PAL_10 13'h0800   // crcstep
`define STT_PAL_11 13'h0001   // load
`define STT_PAL_12 13'h0003   // loadcrc
`define STT_PAL_13 13'h0002   // loadk
`define STT_PAL_14 13'h0007   // push
`define STT_PAL_15 13'h0005   // shift
`define STT_PAL_16 13'h0200   // thalf
`define STT_PAL_17 13'h0100   // trst
`define STT_PAL_18 13'h0025   // cdec, shift
`define STT_PAL_19 13'h0109   // cload, load, trst
`define STT_PAL_20 13'h0009   // cload, load
`define STT_PAL_21 13'h0825   // cdec, crcstep, shift
`define STT_PAL_22 13'h0006   // clr, shift
`define STT_PAL_23 13'h014A   // c2load, cload, loadk, trst

`endif
