#!/usr/bin/env python3
"""Generate rtl/stt_palette_rom.vh: the 24 fixed palette entries as 13-bit constants.

The entry contents come from isa_bench/ (hybridsweep.py's recipe, trained
in-sample on all five benchmarks); the bit layout comes from rtl/ISA_NOTES.md §5.
Regenerate with:  python3 scripts/gen_palette.py
"""
import os
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, os.pardir))
sys.path.insert(0, os.path.join(ROOT, "isa_bench"))

from rowenc import GROUPS, GROUP_BITS, bits_for, encode_actions_grouped   # noqa: E402
from rowformat import SINGLES                                             # noqa: E402
from gensweep import BENCH, SRC                                           # noqa: E402

FIXED = 24

freq = Counter(tuple(sorted(r.act)) for b in BENCH for r in SRC[b](32)[1].rows
               if len(r.act) > 1)
fixed = [()] + sorted(SINGLES) + [s for s, _ in freq.most_common(FIXED - 1 - len(SINGLES))]
assert len(fixed) == FIXED, len(fixed)


def entry_bits(acts):
    """Pack an action set into the 13-bit grouped entry, groups LSB-first."""
    codes = encode_actions_grouped(list(acts))
    v, off = 0, 0
    for (_, choices), c in zip(GROUPS, codes):
        w = bits_for(len(choices))
        v |= c << off
        off += w
    assert off == GROUP_BITS
    return v


lines = [
    "// GENERATED by scripts/gen_palette.py -- do not edit.",
    "// 24 fixed action-set palette entries, 13 bits each (rtl/ISA_NOTES.md section 5).",
    "// Contents from isa_bench/ (hybridsweep.py recipe, in-sample over all five benchmarks).",
    "`ifndef STT_PALETTE_ROM_VH",
    "`define STT_PALETTE_ROM_VH",
    "",
]
for i, acts in enumerate(fixed):
    v = entry_bits(acts)
    label = ", ".join(acts) if acts else "(empty)"
    lines.append(f"`define STT_PAL_{i:02d} 13'h{v:04X}   // {label}")
lines += ["", "`endif", ""]

out = os.path.join(ROOT, "rtl", "stt_palette_rom.vh")
with open(out, "w") as fh:
    fh.write("\n".join(lines))

print(f"\nwrote {out}")
for i, acts in enumerate(fixed):
    print(f"  {i:2}  13'h{entry_bits(acts):04X}  {', '.join(acts) if acts else '(empty)'}")
